"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api, ageFrom, shortAddr } from "@/lib/api/client";
import type { EntityDetail } from "@/types";
import type { DeveloperIdentityCorrelation } from "@/types/developer-correlation";
import { CopyButton } from "@/components/ui/CopyButton";

export default function EntityDetailPage() {
  const params = useParams(); const id = String(params.id || "");
  const [data, setData] = useState<EntityDetail | null>(null); const [correlation, setCorrelation] = useState<DeveloperIdentityCorrelation | null>(null);
  useEffect(() => { if (!id) return; api.entity(id).then(setData).catch(() => setData({ available: false, entity_id: id, message: "API error" })); fetch(`/api/stinky/v1/entity-graph/developer-correlation/${id}?limit=100`, { cache: "no-store", signal: AbortSignal.timeout(12_000) }).then(r => r.ok ? r.json() : null).then(r => setCorrelation(r as DeveloperIdentityCorrelation | null)).catch(() => setCorrelation(null)); }, [id]);
  if (!data) return <div className="p-6 text-sm text-terminal-muted">Loading entity…</div>;
  if (!data.available || !data.entity) return <div className="p-6"><div className="panel p-4 text-sm"><div className="font-medium">Entity not found</div><p className="mt-1 text-xs text-terminal-muted mono">{id}</p></div></div>;
  const e = data.entity; const sharedFunders = correlation?.shared_funders || []; const walletReuse = correlation?.cross_entity_wallet_reuse || []; const deployerBuyer = correlation?.deployer_buyer_recurrence || []; const sharedStructures = correlation?.shared_relationship_structures || []; const repetition = correlation?.repetition_analysis; const motifs = correlation?.network_motifs; const motifRecords = (motifs?.records || []).slice(0,8); const relatedEntityIds = Array.from(new Set([...sharedFunders, ...walletReuse, ...sharedStructures].map(r => String(r.other_entity_id || "").trim()).filter(Boolean))).slice(0,20); const latestKinds = (correlation?.latest_change?.changes || []).map(c => c.kind).filter(Boolean).slice(0,6);
  return <div className="space-y-4 p-4">
    <div className="panel p-4"><h1 className="text-sm font-medium uppercase tracking-wide text-terminal-dim">Entity</h1><div className="mt-2 grid gap-3 text-xs md:grid-cols-4"><div><div className="text-terminal-muted">Primary wallet</div><div className="mt-0.5 flex items-center gap-2 mono">{shortAddr(e.primary_wallet,6)}{e.primary_wallet && <CopyButton value={e.primary_wallet} label="Copy" />}</div></div><div><div className="text-terminal-muted">Type</div><div>{e.entity_type || "—"}</div></div><div><div className="text-terminal-muted">Launches</div><div className="tabular text-lg font-semibold">{e.launch_count ?? 0}</div></div><div><div className="text-terminal-muted">Confidence</div><div className="tabular">{e.confidence != null ? `${(Number(e.confidence)*100).toFixed(0)}%` : "—"}</div></div></div><p className="mt-3 text-2xs text-terminal-muted mono">id {e.entity_id}</p></div>
    <div className="panel p-4 text-[11px]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-terminal-muted">Developer correlation graph</div><p className="mt-1 text-terminal-dim">Observed cross-entity overlaps only. Repetition and motifs are factual structure, not ownership, coordination, fraud, risk, quality, or predictive strength.</p></div><div className="text-right"><div className="text-[9px] uppercase text-terminal-muted">State</div><div className="font-semibold text-terminal-fg">{String(correlation?.status || "NEW-UNKNOWN")}</div></div></div>
      <dl className="mt-3 grid grid-cols-2 gap-2 text-xs md:grid-cols-5 xl:grid-cols-10"><div><dt className="text-terminal-muted">Shared funders</dt><dd className="tabular">{sharedFunders.length}</dd></div><div><dt className="text-terminal-muted">Wallet reuse</dt><dd className="tabular">{walletReuse.length}</dd></div><div><dt className="text-terminal-muted">Deployer→buyer recurrence</dt><dd className="tabular">{deployerBuyer.length}</dd></div><div><dt className="text-terminal-muted">Shared structures</dt><dd className="tabular">{sharedStructures.length}</dd></div><div><dt className="text-terminal-muted">Repeated relationships</dt><dd className="tabular">{repetition?.repeated_relationship_count ?? 0}</dd></div><div><dt className="text-terminal-muted">Multi-launch repetition</dt><dd className="tabular">{repetition?.multi_launch_relationship_count ?? 0}</dd></div><div><dt className="text-terminal-muted">Network motifs</dt><dd className="tabular">{motifs?.motif_count ?? 0}</dd></div><div><dt className="text-terminal-muted">Repeated motifs</dt><dd className="tabular">{motifs?.repeated_motif_count ?? 0}</dd></div><div><dt className="text-terminal-muted">Multi-entity constellations</dt><dd className="tabular">{motifs?.multi_entity_constellation_count ?? 0}</dd></div><div><dt className="text-terminal-muted">Audit snapshots</dt><dd className="tabular">{correlation?.snapshot_count ?? 0}</dd></div></dl>
      <p className="mt-2 text-[10px] text-terminal-muted">Latest factual change: {latestKinds.length ? latestKinds.join(", ") : correlation?.latest_change?.status || "INITIAL_SNAPSHOT"}</p>
      {repetition?.max_temporal_spread_seconds != null && <p className="mt-1 text-[10px] text-terminal-muted">Longest observed repetition span: {Math.round(repetition.max_temporal_spread_seconds / 3600)}h · repetition_is_not_strength_score true</p>}
      {motifRecords.length > 0 && <div className="mt-3"><div className="text-[9px] uppercase tracking-wide text-terminal-muted">Historical network motifs</div><div className="mt-1 grid gap-1">{motifRecords.map((m,i) => <div key={`${m.motif_kind}-${i}`} className="rounded border border-terminal-border/70 px-2 py-1 text-[10px]"><span className="font-medium">{m.motif_state || m.motif_kind || "OBSERVED_MOTIF"}</span><span className="text-terminal-muted"> · {(m.component_kinds || []).join(" + ") || "observed structure"} · related entities {(m.other_entity_ids || []).length} · components {m.component_count ?? 0}</span></div>)}</div><p className="mt-1 text-[9px] text-terminal-dim">motif_is_not_ownership_or_coordination true · motif_is_not_risk_or_quality_score true</p></div>}
      {relatedEntityIds.length > 0 ? <div className="mt-3"><div className="text-[9px] uppercase tracking-wide text-terminal-muted">Related developer entities</div><div className="mt-1 flex flex-wrap gap-2">{relatedEntityIds.map(entityId => <Link key={entityId} href={`/entities/${entityId}`} className="rounded border border-terminal-border px-2 py-1 font-mono text-[10px] hover:text-terminal-accent">{shortAddr(entityId,5)}</Link>)}</div></div> : <p className="mt-3 text-[10px] text-terminal-dim">No cross-entity correlation evidence observed yet.</p>}
      {Array.isArray(correlation?.missing) && correlation!.missing!.length > 0 && <p className="mt-2 text-[10px] text-terminal-dim">UNKNOWN sources: {correlation!.missing!.join(", ")}</p>}<p className="mt-2 text-[10px] text-terminal-dim">ownership_inferred false · coordination_inferred false · intent_inferred false · predictive_authority false · trade_signal false</p></div>
    <div className="panel overflow-x-auto"><div className="border-b border-terminal-border px-3 py-2 text-2xs uppercase text-terminal-muted">Linked wallets</div><table className="w-full text-left text-xs"><thead className="text-2xs text-terminal-muted"><tr className="border-b border-terminal-border"><th className="px-3 py-2">Wallet</th><th className="px-2 py-2">Role</th><th className="px-2 py-2">Link</th><th className="px-2 py-2">Conf</th></tr></thead><tbody>{(data.wallets || []).length === 0 && <tr><td colSpan={4} className="px-3 py-6 text-terminal-muted">No entity_wallets rows.</td></tr>}{(data.wallets || []).map((w,i) => <tr key={i} className="border-b border-terminal-border/40"><td className="px-3 py-1.5">{w.wallet ? <Link href={`/wallets/${w.wallet}`} className="mono hover:text-terminal-accent">{shortAddr(w.wallet,6)}</Link> : "—"}</td><td className="px-2 py-1.5">{w.role || "—"}</td><td className="px-2 py-1.5 text-terminal-dim">{w.link_reason || "—"}</td><td className="px-2 py-1.5 tabular">{w.confidence != null ? `${(Number(w.confidence)*100).toFixed(0)}%` : "—"}</td></tr>)}</tbody></table></div>
    <div className="panel overflow-x-auto"><div className="border-b border-terminal-border px-3 py-2 text-2xs uppercase text-terminal-muted">Launch history (primary deployer)</div><table className="w-full text-left text-xs"><thead className="text-2xs text-terminal-muted"><tr className="border-b border-terminal-border"><th className="px-3 py-2">Token</th><th className="px-2 py-2">When</th><th className="px-2 py-2">Score</th><th className="px-2 py-2">CA</th></tr></thead><tbody>{(data.launches || []).length === 0 && <tr><td colSpan={4} className="px-3 py-6 text-terminal-muted">No token.launch events for primary wallet.</td></tr>}{(data.launches || []).map((l,i) => <tr key={i} className="border-b border-terminal-border/40"><td className="px-3 py-1.5">{l.mint ? <Link href={`/tokens/${l.mint}`} className="hover:text-terminal-accent">{l.symbol || l.name || shortAddr(l.mint)}</Link> : "—"}</td><td className="px-2 py-1.5 tabular">{ageFrom(l.occurred_at)}</td><td className="px-2 py-1.5 tabular">{l.stinky_score != null ? Number(l.stinky_score).toFixed(0) : "—"}</td><td className="px-2 py-1.5 mono text-terminal-dim">{shortAddr(l.mint)}</td></tr>)}</tbody></table></div>
  </div>;
}
