"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api, fmtUsd, shortAddr } from "@/lib/api/client";

type Desk = { system_status?: string; live_data_status?: string; migration_watch_status?: string; intel_version?: string; source?: string; note?: string; gate_status?: { threshold_usd?: number; clamp_usd?: number; live_gate1?: string; note?: string }; last_observation?: { at?: string | null; kind?: string; evidence_label?: string }; next_observation?: { label?: string }; quality_state?: { current?: string }; database?: { status?: string; note?: string }; discord?: { policy?: string; delivery?: string }; active_investigations?: Array<Record<string, unknown>>; investigations?: Array<Record<string, unknown>>; };
type CalibrationChangeItem = { pattern_hash?: string; mint?: string | null; observed_at?: string | null; change_status?: string; change_kinds?: string[]; current_calibration_state?: string | null; evidence_status?: string | null; };
type DeveloperChangeItem = { entity_id?: string; primary_wallet?: string | null; display_label?: string | null; reference_mint?: string | null; history_state?: string | null; observed_at?: string | null; change_status?: string; change_kinds?: string[]; };
type CorrelationChangeItem = { entity_id?: string; primary_wallet?: string | null; display_label?: string | null; correlation_status?: string | null; observed_at?: string | null; change_status?: string; change_kinds?: string[]; };
type MotifOutcomeChangeItem = { entity_id?: string; primary_wallet?: string | null; display_label?: string | null; context_status?: string | null; motif_analogue_count?: number | null; launch_analogue_count?: number | null; outcome_counts?: Record<string, number>; observed_at?: string | null; change_status?: string; change_kinds?: string[]; };

function tone(s: string | undefined) { const u = (s || "UNKNOWN").toUpperCase(); if (["UP","CONNECTED","OBSERVING","SENT","FIRED","OBSERVED","LIVE","KNOWN_HISTORY"].includes(u)) return "text-emerald-400"; if (["DOWN","FAILED"].includes(u)) return "text-rose-400"; if (["DEGRADED","WATCH","DETERIORATING"].includes(u)) return "text-amber-300"; return "text-terminal-muted"; }
function Cell({ label, value, hint }: { label: string; value?: string | number | null; hint?: string }) { const v = value == null || value === "" ? "UNKNOWN" : String(value); return <div className="rounded-md border border-terminal-border bg-[#0c0e0c] px-3 py-2"><div className="text-[9px] font-semibold uppercase tracking-[0.14em] text-terminal-dim">{label}</div><div className={`mt-1 font-mono text-[13px] ${tone(v)}`}>{v}</div>{hint ? <div className="mt-0.5 text-[10px] text-terminal-muted">{hint}</div> : null}</div>; }

export default function OperatorPage() {
  const [desk, setDesk] = useState<Desk | null>(null); const [changes, setChanges] = useState<CalibrationChangeItem[]>([]); const [changeStatus, setChangeStatus] = useState("UNKNOWN"); const [developerChanges, setDeveloperChanges] = useState<DeveloperChangeItem[]>([]); const [developerChangeStatus, setDeveloperChangeStatus] = useState("UNKNOWN"); const [correlationChanges, setCorrelationChanges] = useState<CorrelationChangeItem[]>([]); const [correlationChangeStatus, setCorrelationChangeStatus] = useState("UNKNOWN"); const [motifOutcomeChanges, setMotifOutcomeChanges] = useState<MotifOutcomeChangeItem[]>([]); const [motifOutcomeChangeStatus, setMotifOutcomeChangeStatus] = useState("UNKNOWN"); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let c = false; (async () => { try { const [d, feed, developerFeed, correlationFeed, motifOutcomeFeed] = await Promise.all([
    api.operator(),
    fetch("/api/stinky/v1/entity-graph/calibration-changes?limit=50", { cache: "no-store", signal: AbortSignal.timeout(12_000) }).then(r => r.ok ? r.json() : null).catch(() => null),
    fetch("/api/stinky/v1/entity-graph/developer-changes?limit=50", { cache: "no-store", signal: AbortSignal.timeout(12_000) }).then(r => r.ok ? r.json() : null).catch(() => null),
    fetch("/api/stinky/v1/entity-graph/developer-correlation-changes?limit=50", { cache: "no-store", signal: AbortSignal.timeout(12_000) }).then(r => r.ok ? r.json() : null).catch(() => null),
    fetch("/api/stinky/v1/entity-graph/developer-motif-outcome-changes?limit=50", { cache: "no-store", signal: AbortSignal.timeout(12_000) }).then(r => r.ok ? r.json() : null).catch(() => null),
  ]); if (!c) { setDesk(d as Desk); const f = (feed || {}) as { status?: string; items?: CalibrationChangeItem[] }; setChanges(Array.isArray(f.items) ? f.items : []); setChangeStatus(String(f.status || "UNKNOWN")); const df = (developerFeed || {}) as { status?: string; items?: DeveloperChangeItem[] }; setDeveloperChanges(Array.isArray(df.items) ? df.items : []); setDeveloperChangeStatus(String(df.status || "UNKNOWN")); const cf = (correlationFeed || {}) as { status?: string; items?: CorrelationChangeItem[] }; setCorrelationChanges(Array.isArray(cf.items) ? cf.items : []); setCorrelationChangeStatus(String(cf.status || "UNKNOWN")); const mf = (motifOutcomeFeed || {}) as { status?: string; items?: MotifOutcomeChangeItem[] }; setMotifOutcomeChanges(Array.isArray(mf.items) ? mf.items : []); setMotifOutcomeChangeStatus(String(mf.status || "UNKNOWN")); setError(null); } } catch (e) { if (!c) setError(e instanceof Error ? e.message : "failed"); } finally { if (!c) setLoading(false); } })(); return () => { c = true; }; }, []);
  const inv = (desk?.active_investigations || desk?.investigations || []) as Array<{ mint?: string; symbol?: string | null; lifecycle?: string; gate_volume?: number | null; current_volume?: number | null; current_quality?: string; evidence_label?: string; next_tick?: { label?: string }; }>;
  return <div className="flex h-full min-h-0 flex-col"><header className="shrink-0 border-b border-terminal-border px-4 py-3"><h1 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-terminal-dim">Operator</h1><p className="mt-1 text-[11px] text-terminal-muted">First live investigation desk. UNKNOWN is UNKNOWN. Policy fired is not delivery. Not a buy.{desk?.intel_version ? ` ${desk.intel_version}.` : ""}</p></header>
  {error && <p className="border-b border-rose-500/30 bg-rose-500/10 px-4 py-2 text-xs text-rose-300">API: {error}</p>}{loading && <p className="p-8 text-center text-sm text-terminal-muted">Loading operator desk…</p>}
  {!loading && desk && <div className="min-h-0 flex-1 space-y-3 overflow-auto p-4">
    <section className="grid grid-cols-2 gap-2 md:grid-cols-4"><Cell label="System" value={desk.system_status} hint={desk.source} /><Cell label="Live data" value={desk.live_data_status} hint="DexScreener" /><Cell label="Migration watch" value={desk.migration_watch_status} hint="Solana WS" /><Cell label="Gate 1" value={desk.gate_status?.live_gate1} hint={`$${Number(desk.gate_status?.threshold_usd || 150000) / 1000}k / clamp $${Number(desk.gate_status?.clamp_usd || 200000) / 1000}k`} /><Cell label="Database" value={desk.database?.status} hint={desk.database?.note} /><Cell label="Discord policy" value={desk.discord?.policy} hint="FIRED is not SENT" /><Cell label="Discord delivery" value={desk.discord?.delivery} /><Cell label="Quality" value={desk.quality_state?.current} /></section>
    <section className="overflow-hidden rounded-md border border-terminal-border"><header className="flex items-center justify-between border-b border-terminal-border px-3 py-2"><div><div className="text-[9px] font-semibold uppercase tracking-wider text-terminal-dim">Historical motif outcome changes · {motifOutcomeChanges.length}</div><div className="mt-0.5 text-[10px] text-terminal-muted">Persisted historical analogue deltas only. Outcome resolution is factual history, not prediction or a trade signal.</div></div><span className={`text-[10px] ${tone(motifOutcomeChangeStatus)}`}>{motifOutcomeChangeStatus}</span></header>{motifOutcomeChanges.length === 0 ? <p className="px-3 py-5 text-center text-[11px] text-terminal-muted">No changed motif-outcome snapshots are visible yet.</p> : <table className="w-full text-left text-[10px]"><thead className="text-[9px] uppercase tracking-wider text-terminal-muted"><tr><th className="px-3 py-2">Developer</th><th className="px-2 py-2">Latest outcome-context change</th><th className="px-2 py-2">Analogues</th><th className="px-2 py-2">R/H/F/U</th><th className="px-2 py-2">Observed</th></tr></thead><tbody>{motifOutcomeChanges.map(r => <tr key={`${r.entity_id}-${r.observed_at}`} className="border-t border-terminal-border/60"><td className="px-3 py-1.5 font-mono">{r.entity_id ? <Link href={`/entities/${r.entity_id}`} className="hover:text-terminal-accent">{r.display_label || shortAddr(r.primary_wallet || r.entity_id, 5)}</Link> : "UNKNOWN"}</td><td className="px-2 py-1.5 text-terminal-dim">{(r.change_kinds || []).join(", ") || r.change_status || "UNKNOWN"}</td><td className="px-2 py-1.5 tabular">{r.motif_analogue_count ?? 0} / {r.launch_analogue_count ?? 0}</td><td className="px-2 py-1.5 font-mono text-terminal-muted">{r.outcome_counts?.RUNNER ?? 0}/{r.outcome_counts?.HELD ?? 0}/{r.outcome_counts?.FADE ?? 0}/{r.outcome_counts?.UNKNOWN ?? 0}</td><td className="px-2 py-1.5 font-mono text-terminal-muted">{r.observed_at ? r.observed_at.slice(0,19) : "UNKNOWN"}</td></tr>)}</tbody></table>}</section>
    <section className="overflow-hidden rounded-md border border-terminal-border"><header className="flex items-center justify-between border-b border-terminal-border px-3 py-2"><div><div className="text-[9px] font-semibold uppercase tracking-wider text-terminal-dim">Developer correlation changes · {correlationChanges.length}</div><div className="mt-0.5 text-[10px] text-terminal-muted">New or unavailable shared funders, wallet reuse, deployer→buyer recurrence, and relationship structures. Observed overlap is not ownership or coordination.</div></div><span className={`text-[10px] ${tone(correlationChangeStatus)}`}>{correlationChangeStatus}</span></header>{correlationChanges.length === 0 ? <p className="px-3 py-5 text-center text-[11px] text-terminal-muted">No changed correlation snapshots are visible yet.</p> : <table className="w-full text-left text-[10px]"><thead className="text-[9px] uppercase tracking-wider text-terminal-muted"><tr><th className="px-3 py-2">Developer</th><th className="px-2 py-2">Latest correlation change</th><th className="px-2 py-2">State</th><th className="px-2 py-2">Observed</th></tr></thead><tbody>{correlationChanges.map(r => <tr key={`${r.entity_id}-${r.observed_at}`} className="border-t border-terminal-border/60"><td className="px-3 py-1.5 font-mono">{r.entity_id ? <Link href={`/entities/${r.entity_id}`} className="hover:text-terminal-accent">{r.display_label || shortAddr(r.primary_wallet || r.entity_id, 5)}</Link> : "UNKNOWN"}</td><td className="px-2 py-1.5 text-terminal-dim">{(r.change_kinds || []).join(", ") || r.change_status || "UNKNOWN"}</td><td className={`px-2 py-1.5 ${tone(r.correlation_status || undefined)}`}>{r.correlation_status || "UNKNOWN"}</td><td className="px-2 py-1.5 font-mono text-terminal-muted">{r.observed_at ? r.observed_at.slice(0,19) : "UNKNOWN"}</td></tr>)}</tbody></table>}</section>
    <section className="overflow-hidden rounded-md border border-terminal-border"><header className="flex items-center justify-between border-b border-terminal-border px-3 py-2"><div><div className="text-[9px] font-semibold uppercase tracking-wider text-terminal-dim">Developer evidence changes · {developerChanges.length}</div><div className="mt-0.5 text-[10px] text-terminal-muted">Cross-developer factual history deltas. NEW-UNKNOWN is not good or bad.</div></div><span className={`text-[10px] ${tone(developerChangeStatus)}`}>{developerChangeStatus}</span></header>{developerChanges.length === 0 ? <p className="px-3 py-5 text-center text-[11px] text-terminal-muted">No changed developer snapshots are visible yet.</p> : <table className="w-full text-left text-[10px]"><thead className="text-[9px] uppercase tracking-wider text-terminal-muted"><tr><th className="px-3 py-2">Developer</th><th className="px-2 py-2">Reference mint</th><th className="px-2 py-2">Latest change</th><th className="px-2 py-2">History</th><th className="px-2 py-2">Observed</th></tr></thead><tbody>{developerChanges.map(r => <tr key={`${r.entity_id}-${r.observed_at}`} className="border-t border-terminal-border/60"><td className="px-3 py-1.5 font-mono">{r.entity_id ? <Link href={`/entities/${r.entity_id}`} className="hover:text-terminal-accent">{r.display_label || shortAddr(r.primary_wallet || r.entity_id,5)}</Link> : "UNKNOWN"}</td><td className="px-2 py-1.5 font-mono">{r.reference_mint ? <Link href={`/tokens/${r.reference_mint}`} className="hover:text-terminal-accent">{shortAddr(r.reference_mint,5)}</Link> : "UNKNOWN"}</td><td className="px-2 py-1.5 text-terminal-dim">{(r.change_kinds || []).join(", ") || r.change_status || "UNKNOWN"}</td><td className={`px-2 py-1.5 ${tone(r.history_state || undefined)}`}>{r.history_state || "NEW-UNKNOWN"}</td><td className="px-2 py-1.5 font-mono text-terminal-muted">{r.observed_at ? r.observed_at.slice(0,19) : "UNKNOWN"}</td></tr>)}</tbody></table>}</section>
    <section className="overflow-hidden rounded-md border border-terminal-border"><header className="flex items-center justify-between border-b border-terminal-border px-3 py-2"><div><div className="text-[9px] font-semibold uppercase tracking-wider text-terminal-dim">Calibration evidence changes · {changes.length}</div><div className="mt-0.5 text-[10px] text-terminal-muted">Cross-investigation factual deltas only. No score, forecast, risk grade, or trade signal.</div></div><span className={`text-[10px] ${tone(changeStatus)}`}>{changeStatus}</span></header>{changes.length === 0 ? <p className="px-3 py-5 text-center text-[11px] text-terminal-muted">No changed synthesis snapshots are visible yet.</p> : <table className="w-full text-left text-[10px]"><thead className="text-[9px] uppercase tracking-wider text-terminal-muted"><tr><th className="px-3 py-2">Mint</th><th className="px-2 py-2">Latest change</th><th className="px-2 py-2">Calibration state</th><th className="px-2 py-2">Evidence</th><th className="px-2 py-2">Observed</th></tr></thead><tbody>{changes.map(r => <tr key={`${r.pattern_hash}-${r.observed_at}`} className="border-t border-terminal-border/60"><td className="px-3 py-1.5 font-mono">{r.mint ? <Link href={`/tokens/${r.mint}`} className="hover:text-terminal-accent">{shortAddr(r.mint,5)}</Link> : "UNKNOWN"}</td><td className="px-2 py-1.5 text-terminal-dim">{(r.change_kinds || []).join(", ") || r.change_status || "UNKNOWN"}</td><td className="px-2 py-1.5">{r.current_calibration_state || "UNKNOWN"}</td><td className="px-2 py-1.5">{r.evidence_status || "UNKNOWN"}</td><td className="px-2 py-1.5 font-mono text-terminal-muted">{r.observed_at ? r.observed_at.slice(0,19) : "UNKNOWN"}</td></tr>)}</tbody></table>}</section>
    <section className="grid gap-2 md:grid-cols-2"><div className="rounded-md border border-terminal-border px-3 py-2 text-[11px]"><div className="text-[9px] uppercase tracking-wider text-terminal-dim">Last observation</div><p className="mt-1 font-mono">{desk.last_observation?.at || "UNKNOWN"} · {desk.last_observation?.kind || "UNKNOWN"} · {desk.last_observation?.evidence_label || "UNKNOWN"}</p></div><div className="rounded-md border border-terminal-border px-3 py-2 text-[11px]"><div className="text-[9px] uppercase tracking-wider text-terminal-dim">Next observation</div><p className="mt-1 font-mono">{desk.next_observation?.label || "UNKNOWN"}</p></div></section><p className="text-[10px] text-terminal-dim">{desk.gate_status?.note} {desk.note}</p>
    <section className="overflow-hidden rounded-md border border-terminal-border"><header className="border-b border-terminal-border px-3 py-2 text-[9px] font-semibold uppercase tracking-wider text-terminal-dim">Investigations · {inv.length}</header>{inv.length === 0 ? <p className="px-3 py-6 text-center text-[12px] text-terminal-muted">LIVE GATE-1: {desk.gate_status?.live_gate1 || "UNKNOWN"}. Empty is empty.</p> : <table className="w-full text-left text-[11px]"><thead className="text-[9px] uppercase tracking-wider text-terminal-muted"><tr><th className="px-3 py-2">Mint</th><th className="px-2 py-2">Lifecycle</th><th className="px-2 py-2">Gate vol</th><th className="px-2 py-2">Now vol</th><th className="px-2 py-2">Quality</th><th className="px-2 py-2">Next</th><th className="px-2 py-2">Label</th></tr></thead><tbody>{inv.map(r => <tr key={String(r.mint)} className="border-t border-terminal-border"><td className="px-3 py-1.5 font-mono"><Link href={`/tokens/${r.mint}`} className="hover:text-terminal-accent">{r.symbol || shortAddr(String(r.mint || ""),4)}</Link></td><td className={`px-2 py-1.5 ${tone(r.lifecycle)}`}>{r.lifecycle}</td><td className="px-2 py-1.5">{fmtUsd(r.gate_volume ?? null)}</td><td className="px-2 py-1.5">{fmtUsd(r.current_volume ?? null)}</td><td className="px-2 py-1.5">{r.current_quality || "UNKNOWN"}</td><td className="px-2 py-1.5">{r.next_tick?.label || "UNKNOWN"}</td><td className="px-2 py-1.5">{r.evidence_label || "UNKNOWN"}</td></tr>)}</tbody></table>}</section>
  </div>}</div>;
}